export const SET_ALL_PRODUCTS = "SET_ALL_PRODUCTS";
export const ADD_TO_CART = "ADD_TO_CART";
export const ADJUST_ITEM_QTY = "ADJUST_ITEM_QTY";
export const ADJUST_ATTRIBUTE_VALUE = "ADJUST_ATTRIBUTE_VALUE";
export const SET_CURRENCY = "SET_CURRENCY";
